title: Juan Raul Padron Griffe
description: > # this means to ignore newlines until "baseurl:"
  Computer scientist passionate about computer graphics, computer vision and machine learning.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://juanraul8.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Juan Raul Padron # add your name
author-img: juanraul.jpg # add your photo
about-author: Hola! I have just finished my MSc Informatics at Technical University of Munich. Currently, I am looking for a PhD position. # add description
social-twitter: JuanRaulPadron# add your Twitter handle
social-github: juanraul8 # add your Github handle
social-linkedin: juan-raul-padron-griffe # add your Linkedin handle
social-email: juanraul.padron@gmail.com # add your Email address

# Disqus
discus-identifier: Juan Raul Padron Griffe # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
